### ISSUE TITLE
Upgrading Requirements.txt causes breaking changes.

### ISSUE THREAD

**Issue by thedayisntgray** [maxdotio/ai-search-training#1]
Hey @binarymax ,

Just a heads up. I noticed that upgrading the requirements.txt via [this pr](https://github.com/maxdotio/ai-search-training/commit/a1f1370d28de05df25345d2c9e57a77534682ce7) creates a breaking change. Specifically the issue I see is with the sentence-transformers library. We either need to downgrade that one gem or rework the examples to use the correct import method.

I'll plan to take a look further look sometime this weekend.

But I did confirm that reverting the requirements.txt file fixes this issue for sentence-transformers.
![Screenshot 2024-11-30 at 11 25 50 AM](https://github.com/user-attachments/assets/e8507d99-5fee-45d8-9d34-f495b5a345ec)

**Comment by binarymax** [comment]
Hey!  Yeah I ran into that exact same issue.  You'll need to rebuild the entire docker for this to work:

```docker compose build```

It's fine to keep your Ruby port the same.

**Comment by thedayisntgray** [comment]
You're are right! Closing this.
